version: "3"
services:
  ccweb:
    build: .
    container_name: ccweb
    hostname: ccweb
    image: ccweb
    volumes:
      - .:/app
    ports:
      - "8000:80"
    networks:
      - my_network
  
networks:
  my_network:
    external: true 